import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const MorrisRoman = localFont({
  src: './fonts/MorrisRomanBlack.woff2',
  variable: '--font-morris-roman',
  weight: '100 900',
  fallback: ['serif'],
})
const ParmaPetit = localFont({
  src: './fonts/ParmaPetit-Normal.woff2',
  variable: '--font-parma-petit',
  weight: '100 900',
  fallback: ['serif'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${MorrisRoman.variable} ${ParmaPetit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
